## Virtual Developer Environment

Vagrant.configure("2") do |config|

    config.vm.box = "donrwalsh/pick1-dev" 
    config.vm.box_version = "1.0.2"
    
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
  config.vm.synced_folder "../database", "/vagrant/database"
  config.vm.synced_folder "../python", "/vagrant/python"
  config.vm.synced_folder "../server", "/vagrant/server"
	config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.network "forwarded_port", guest: 3306, host: 3306
    end
end
